name: Build

concurrency:
  group: build_${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

env:
  JAVET_BUDDY_VERSION: 0.3.0

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 8

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.10.2

    - name: Build the Artifact
      run: |
        gradle build test generatePomFileForGeneratePomPublication

    - name: Upload the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: javet-buddy-${{ env.JAVET_BUDDY_VERSION }}
        path: |
          build/libs/*.jar
          build/libs/*.pom
